name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      BE_URL: http://localhost:6900

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Retrieve Git history, needed to verify commits

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Copy env.example to .env
        run: cp .env.example .env

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.1.1
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Cache node_modules & .next/cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules/
            .next/cache/
          key: ${{ runner.os }}-node-next-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-next-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Linter
        run: pnpm run lint

      - name: Type checking
        run: pnpm run check-types
